version: '3.9'

networks:
  default:

volumes:
  postgres_db_data:

services:
  # db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.db
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres_db_data:/var/lib/postgresql/data
  #   networks:
  #     default:

  cozastore-app:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - db
    restart: always
    ports:
      - '80:3000'
    # entrypoint: /usr/local/bin/start.sh
    networks:
      - default
