import type { Metadata } from "next";
import Category from "../db/categories.json";
import Image from "next/image";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Category Page",
  description: "Generated by create next app",
};

type category = {
  id: string;
  name: string;
  description: string;
  image: string;
};

type CategoryCardProps = {
  data: category;
};
const CategoryCard: React.FC<CategoryCardProps> = ({ data }) => {
  return (
    <Link href={`/category/${data.id}`}>
      <div className="w-full sm:w-[280px] duration-100 hover:scale-105 transition-all">
        <div className="w-full h-full">
          <Image
            width={280}
            height={180}
            src={data.image}
            className="w-full h-full object-contain"
            alt=""
          />
        </div>
        <div className="mt-3 bg-slate-100 rounded-xl border p-3">
          <div className="text-xl font-semibold">{data.name}</div>
          <div className="truncate text-slate-500 ">{data.description}</div>
        </div>
      </div>
    </Link>
  );
};

export default function Page() {
  return (
    <div className="flex justify-center">
      <div className="lg:w-[1280px] mt-6">
        <div className="flex mx-3 justify-center flex-col">
          <h1 className="text-5xl mb-9 font-bold">Category Page</h1>
          <div className="justify-center justify-items-center items-center grid grid-cols-1 lg:grid-cols-3 xl:grid-cols-4 gap-8 sm:grid-cols-2">
            {Category.map((category: category) => (
              <CategoryCard key={category.id} data={category} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
