import CartProvider from './context/CartProvider'
import './globals.css'
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import localFont from 'next/font/local'
import React from 'react'

export const metadata: Metadata = {
  title: 'CozaStore',
  description: 'Generated by create next app',
  icons: {
    icon: '/Designer.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <body className="bg-[#ececec5a]">
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
