import './globals.css'
import type { Metadata } from 'next'
<<<<<<< HEAD
import Navbar from './components/Navbar'
=======
>>>>>>> origin/main
import localFont from 'next/font/local'
import React from 'react'
import UserProvider from './context/UserProvider'

export const metadata: Metadata = {
  title: 'CozaStore',
  description: 'Generated by create next app',
  icons: {
    icon: '/Designer.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
<<<<<<< HEAD
      <body className="bg-[#ececec5a] overscroll-none">
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
=======
      <body className="webkit-font-smoothing font-ppneue bg-[#ececec5a]">
        <UserProvider>{children}</UserProvider>
>>>>>>> origin/main
      </body>
    </html>
  )
}
