import CartProvider from "./context/CartProvider";
import "./globals.css";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "CozaStore",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

const DynamicNavbar = dynamic(() => import("./components/Navbar"), {
  ssr: false, // This ensures the component is not server-side rendered
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#f6f6f6]">
        <CartProvider>
          <Navbar />
          {/* <DynamicNavbar /> */}
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
